baseURL = 'https://tomrake.github.io/the-invaders/'
languageCode = 'en-us'
title = 'The Invaders: CL SDL on Window Proving Ground.'
theme = "m10c"

author = "Tom Rake"
[params]
  description = "A space invaders clone in Common Lisp. And sdl testing for windows."
  avatar = "2665605.jfif"

[[params.social]]
  icon = "github-dark"
  name = "Github"
  url = "https://github.com/tomrake"

[[params.social]]
  icon = "reddit"
  name = "tomrake"
  url = "https://reddit.com/user/tomrake"

[[params.social]]
  icon = "mastodon"
  name = "Mastodon"
  url = "https://mastodon.social/@tomrake"

[[params.social]]
  icon = "discord"
  name = "Discord"
  url = "https://discordapp.com/users/tomrake1957#0816"

[[menu.main]]
 name = "Home"
 url = "/"
 weight = "10"


[[menu.main]]
 name = "About"
 url = "/about/"
 weight = "20"